services:
  apache:
    image: apachecgi:1
    build: .
    container_name: apache
    hostname: apache
    ports:
      - 8080:80
    privileged: true

  openvas:
    image: mikesplain/openvas:latest
    container_name: openvas
    hostname: openvas
    ports:
      - 443:443
    privileged: true

networks:
  default:
    name: rede_virtual